repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --config D:\Python\style/.black .
        language: system
        types: [ python ]
        pass_filenames: false